import { agreement, assignmentColumns, desiredEffects, possibleSideEffects, reviewQuestions, type Activity, type Assignment } from '@/data/team';

export type Experiment = { hypothesis: string; duration: string; effects: string[]; sideEffects: string[] };
export function ChoiceList({ title, options, selected, onChange }: { title: string; options: string[]; selected: string[]; onChange: (value: string[]) => void }) {
  return <fieldset className="tl-choice-list"><legend>{title}</legend>{options.map((option) => <label className="tl-check" key={option}><input type="checkbox" checked={selected.includes(option)} onChange={() => onChange(selected.includes(option) ? selected.filter((value) => value !== option) : [...selected, option])} /><span>{option}</span></label>)}</fieldset>;
}
export function ExperimentEditor({ activity, value, onChange }: { activity: Activity; value: Experiment; onChange: (value: Experiment) => void }) {
  return <div className="tl-experiment-editor"><p className="tl-small">Wir untersuchen</p><h2>{activity.title}</h2><label className="tl-field-label" htmlFor="team-hypothesis">Unsere Hypothese</label><textarea id="team-hypothesis" value={value.hypothesis} onChange={(event) => onChange({ ...value, hypothesis: event.target.value })} maxLength={1500} rows={4} /><label className="tl-field-label" htmlFor="team-duration">Zeitraum</label><select id="team-duration" value={value.duration} onChange={(event) => onChange({ ...value, duration: event.target.value })}>{['2 Wochen', '3 Wochen', '4 Wochen'].map((duration) => <option key={duration}>{duration}</option>)}</select><div className="tl-observation-grid"><ChoiceList title="Woran merken wir, dass es sinnvoll ist?" options={desiredEffects} selected={value.effects} onChange={(effects) => onChange({ ...value, effects })} /><ChoiceList title="Worauf achten wir bewusst?" options={possibleSideEffects} selected={value.sideEffects} onChange={(sideEffects) => onChange({ ...value, sideEffects })} /></div><section className="tl-agreement"><h2>Für diesen Test vereinbaren wir</h2><ul>{agreement.map((item) => <li key={item}>{item}</li>)}</ul></section></div>;
}
export function ExperimentSummary({ activity, assignments, needs, value }: { activity: Activity; assignments: Record<string, Assignment>; needs: string[]; value: Experiment }) {
  return <article className="tl-summary" aria-label="Experiment-Canvas"><section><h2>Aufgabe</h2><p>{activity.title}</p></section><section><h2>Hypothese</h2><p>{value.hypothesis}</p></section><section className="tl-summary-wide"><h2>Aufteilung Mensch & AI</h2><div className="tl-summary-mapping">{assignmentColumns.map((column) => <div key={column.id}><h3>{column.title}</h3><ul>{activity.subtasks.filter((task) => assignments[task.id] === column.id).map((task) => <li key={task.id}>{task.title}{task.judgement && column.id === 'ai' ? ' (nur Vorbereitung; Beurteilung bleibt beim Team)' : ''}</li>)}</ul>{!activity.subtasks.some((task) => assignments[task.id] === column.id) && <p>Keine Aufgabe zugeordnet.</p>}</div>)}</div></section><section><h2>Voraussetzungen im Team</h2>{needs.length ? <ul>{needs.map((need) => <li key={need}>{need}</li>)}</ul> : <p>Noch keine Voraussetzungen festgehalten – vor einem echten Versuch klären.</p>}</section><section><h2>Zeitraum</h2><p>{value.duration}</p><p className="tl-small">Geplanter Versuch, keine Terminbuchung.</p></section><section><h2>Gewünschte Wirkung</h2><ul>{value.effects.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h2>Mögliche Nebenwirkungen</h2><ul>{value.sideEffects.map((item) => <li key={item}>{item}</li>)}</ul></section><section className="tl-summary-wide"><h2>Review-Fragen</h2><ul>{reviewQuestions.map((item) => <li key={item}>{item}</li>)}</ul></section></article>;
}
