import { cvExperience, demoDocuments, motivationLetter, openQuestions, requirements, type DocumentId } from '@/data/recruiting';

export function Preparation({ documents }: { documents: DocumentId[] }) {
  const gaps = openQuestions.filter((item) => documents.includes(item.requires));
  return <div className="preparation-stack"><p className="source-summary">Einbezogen: {demoDocuments.filter((doc) => documents.includes(doc.id)).map((doc) => doc.label).join(', ')}</p>
    <section className="preparation-panel"><div className="panel-heading"><span className="section-number">01</span><h2>Kernanforderungen der Rolle</h2></div>{documents.includes('role') ? <><p className="source-label">Quelle: Stellenprofil · Change Manager Digital Workplace</p><ul className="requirement-list">{requirements.map((item) => <li key={item}>{item}</li>)}</ul></> : <p>Kein Stellenprofil ausgewählt. Rollenanforderungen werden deshalb nicht aus Unterlagen abgeleitet. Ergänze das Stellenprofil über «Zurück», wenn du es einbeziehen möchtest.</p>}</section>
    <section className="preparation-panel"><div className="panel-heading"><span className="section-number">02</span><h2>Relevante Erfahrungen</h2></div>{documents.includes('cv') ? <div className="evidence-grid">{cvExperience.map((item) => <article key={item.id}><h3>{item.title}</h3><p>{item.detail}</p><p className="source-label">{item.source}</p><details><summary>Textstelle ansehen</summary><blockquote>{item.excerpt}</blockquote></details></article>)}</div> : <p>Kein Lebenslauf ausgewählt. Ohne diese Quelle werden keine konkreten beruflichen Erfahrungen behauptet.</p>}{documents.includes('letter') && <div className="motivation-excerpt"><h3>Motivation aus dem Schreiben</h3><p>{motivationLetter.paragraphs[0]}</p><p className="source-label">Quelle: Motivationsschreiben · Selbstauskunft, kein Erfahrungsnachweis</p></div>}</section>
    <section className="preparation-panel open-points"><div className="panel-heading"><span className="section-number">03</span><h2>Offene Punkte</h2></div><p className="r-muted">Fehlende Angaben sind Gesprächsanlässe. Sie belegen nicht, dass eine Fähigkeit fehlt.</p>{gaps.length ? gaps.map((item) => <article key={item.title}><h3>{item.title}</h3><p>{item.detail}</p><p className="source-label">{item.source}</p></article>) : <article><h3>Erfahrungen im Gespräch erkunden</h3><p>Es wurden keine persönlichen Demo-Unterlagen ausgewählt. Die Fragen können sich nur auf die Rolle und deinen Interviewfokus beziehen.</p></article>}</section>
  </div>;
}
